/*
 * Simple RTEMS configuration
 */
#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER
#define CONFIGURE_UNLIMITED_OBJECTS
#define CONFIGURE_UNIFIED_WORK_AREAS
#define CONFIGURE_RTEMS_INIT_TASKS_TABLE
#define CONFIGURE_INIT
#define CONFIGURE_MAXIMUM_FILE_DESCRIPTORS 50 // 文件句柄数量
#define CONFIGURE_FILESYSTEM_DOSFS
#define CONFIGURE_APPLICATION_NEEDS_LIBBLOCK
#define RTEMS_SHELL
#define RTEMS_SHELL_START
#define RTEMS_SHELL_COMMANDS_INIT
#define RTEMS_ENABLE_NETWORKING 1 // 如果需要网络 shell


#include <rtems/confdefs.h>
